import { describe, it, expect, afterEach } from 'vitest'
import { mkdtempSync, rmSync, statSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  isLoopbackHost,
  resolveAuth,
  bearerFromHeader,
  tokensMatch,
  isGatedApiPath,
  generateToken,
  loadOrCreatePersistedToken,
} from './auth'

describe('isLoopbackHost', () => {
  it('treats loopback names/addresses as loopback', () => {
    for (const h of ['127.0.0.1', 'localhost', '::1', '[::1]', 'LOCALHOST', '0:0:0:0:0:0:0:1']) {
      expect(isLoopbackHost(h)).toBe(true)
    }
  })
  it('treats tailscale / LAN / wildcard binds as non-loopback', () => {
    for (const h of ['my-box.ts.net', '100.64.0.1', '0.0.0.0', '192.168.1.10']) {
      expect(isLoopbackHost(h)).toBe(false)
    }
  })
})

describe('resolveAuth', () => {
  it('requires NOTHING on a loopback bind', () => {
    expect(resolveAuth('127.0.0.1', {})).toEqual({
      required: false,
      token: '',
      autoGenerated: false,
    })
  })
  it('uses AGENT_DECK_TOKEN when set on a non-loopback bind', () => {
    expect(resolveAuth('box.ts.net', { AGENT_DECK_TOKEN: 'sekret' })).toEqual({
      required: true,
      token: 'sekret',
      autoGenerated: false,
    })
  })
  it('auto-generates a token on a non-loopback bind with no env token', () => {
    const auth = resolveAuth('box.ts.net', {}, () => 'GENERATED')
    expect(auth).toEqual({ required: true, token: 'GENERATED', autoGenerated: true })
  })
  it('ignores an empty/whitespace env token and auto-generates instead', () => {
    const auth = resolveAuth('box.ts.net', { AGENT_DECK_TOKEN: '   ' }, () => 'GEN')
    expect(auth.autoGenerated).toBe(true)
    expect(auth.token).toBe('GEN')
  })
  it('can force auth on a loopback bind for reverse-proxy deployments', () => {
    expect(resolveAuth('127.0.0.1', { AGENT_DECK_FORCE_AUTH: '1' }, () => 'GEN')).toEqual({
      required: true,
      token: 'GEN',
      autoGenerated: true,
    })
    expect(resolveAuth('127.0.0.1', { AGENT_DECK_REMOTE: '1', AGENT_DECK_TOKEN: 'T' })).toEqual({
      required: true,
      token: 'T',
      autoGenerated: false,
    })
  })
})

describe('generateToken', () => {
  it('produces a 64-char hex string (256 bits) and is unique', () => {
    const a = generateToken()
    const b = generateToken()
    expect(a).toMatch(/^[0-9a-f]{64}$/)
    expect(a).not.toBe(b)
  })
})

describe('loadOrCreatePersistedToken', () => {
  let dir: string
  afterEach(() => {
    if (dir) rmSync(dir, { recursive: true, force: true })
  })

  it('creates a token on first call, then REUSES the same one across calls (stable across restarts)', () => {
    dir = mkdtempSync(join(tmpdir(), 'ad-token-'))
    const path = join(dir, 'nested', 'auth-token')
    const first = loadOrCreatePersistedToken(path)
    expect(first).toMatch(/^[0-9a-f]{64}$/)
    // A second call (a "restart") returns the SAME persisted token, not a fresh one.
    expect(loadOrCreatePersistedToken(path)).toBe(first)
    expect(readFileSync(path, 'utf8')).toBe(first)
  })

  it('writes the token file 0600 (owner read/write only)', () => {
    dir = mkdtempSync(join(tmpdir(), 'ad-token-'))
    const path = join(dir, 'auth-token')
    loadOrCreatePersistedToken(path)
    expect(statSync(path).mode & 0o777).toBe(0o600)
  })

  it('falls back to an in-memory token when the path is unwritable (never throws)', () => {
    // Parent is a regular FILE, so mkdir/write fail cleanly (ENOTDIR) — the function
    // must swallow it and still return a usable token (it just won't persist).
    dir = mkdtempSync(join(tmpdir(), 'ad-token-'))
    const fileAsParent = join(dir, 'a-file')
    writeFileSync(fileAsParent, 'x')
    const token = loadOrCreatePersistedToken(join(fileAsParent, 'auth-token'))
    expect(token).toMatch(/^[0-9a-f]{64}$/)
  })
})

describe('bearerFromHeader', () => {
  it('extracts the token from a Bearer header (case-insensitive)', () => {
    expect(bearerFromHeader('Bearer abc123')).toBe('abc123')
    expect(bearerFromHeader('bearer  abc123  ')).toBe('abc123')
  })
  it('returns null for missing / malformed headers', () => {
    expect(bearerFromHeader(undefined)).toBeNull()
    expect(bearerFromHeader('Basic abc')).toBeNull()
    expect(bearerFromHeader('abc')).toBeNull()
  })
})

describe('tokensMatch', () => {
  it('matches identical tokens', () => {
    expect(tokensMatch('abc', 'abc')).toBe(true)
  })
  it('rejects mismatches, length differences, and empties', () => {
    expect(tokensMatch('abc', 'abd')).toBe(false)
    expect(tokensMatch('abc', 'ab')).toBe(false)
    expect(tokensMatch('abc', null)).toBe(false)
    expect(tokensMatch('', 'abc')).toBe(false)
    expect(tokensMatch('abc', undefined)).toBe(false)
  })
})

describe('isGatedApiPath', () => {
  it('gates /api/* except the public health probe', () => {
    expect(isGatedApiPath('/api/agent-deck/sessions')).toBe(true)
    expect(isGatedApiPath('/api/agent-deck/files/roots?root=x')).toBe(true)
    expect(isGatedApiPath('/api/agent-deck/auth/check')).toBe(true)
    expect(isGatedApiPath('/api/agent-deck/health')).toBe(false)
  })
  it('does not gate non-API paths (SPA shell, assets, sockets)', () => {
    expect(isGatedApiPath('/')).toBe(false)
    expect(isGatedApiPath('/assets/app.js')).toBe(false)
    expect(isGatedApiPath('/socket.io/?EIO=4')).toBe(false)
  })
})
