/**
 * C1 integration — the auth gate wired into the real Fastify app + served shell.
 * Hermetic: no dashboard/gateway needed. The onRequest hook fires before routing
 * so a gated `/api/*` path 401s before it would 404, which is exactly the gate
 * we want to prove.
 */
import { describe, it, expect, afterEach, beforeAll, afterAll, vi } from 'vitest'
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { buildApp } from '../app'
import type { ServerConfig } from '../config'
import { isLoopbackHost, type AuthConfig } from './auth'

let webDist: string
beforeAll(() => {
  webDist = mkdtempSync(join(tmpdir(), 'agent-deck-auth-dist-'))
  writeFileSync(
    join(webDist, 'index.html'),
    '<!doctype html><html><head><title>Agent Deck</title></head><body><div id="root"></div></body></html>',
  )
})
afterAll(() => {
  rmSync(webDist, { recursive: true, force: true })
})

function makeConfig(host: string, staticRoot: string | null = null): ServerConfig {
  const remote = !isLoopbackHost(host)
  return {
    host,
    port: 7878,
    remote,
    trustedHosts: [],
    terminalEnabled: !remote,
    terminalAllowHome: false,
    terminalParkGraceMs: 60_000,
    hermesHome: '/tmp/hermes-test-home',
    hermesGatewayUrl: 'http://127.0.0.1:8643',
    hermesBin: '/tmp/hermes',
    hermesApiKey: null,
    hermesDashboardUrl: 'http://127.0.0.1:9123',
    hermesDashboardHost: '127.0.0.1:9123',
    webClientRoot: staticRoot,
    mcpCatalogDir: '/tmp/optional-mcps',
  }
}

const LOOPBACK_AUTH: AuthConfig = { required: false, token: '', autoGenerated: false }
const REMOTE_AUTH: AuthConfig = { required: true, token: 'SECRET_TOKEN', autoGenerated: false }

let app: Awaited<ReturnType<typeof buildApp>> | undefined
afterEach(async () => {
  vi.restoreAllMocks()
  await app?.close()
  app = undefined
})

describe('loopback bind = frictionless (no auth)', () => {
  it('serves a gated-looking /api path WITHOUT a token (404 from routing, not 401)', async () => {
    app = await buildApp(makeConfig('127.0.0.1'), LOOPBACK_AUTH)
    const res = await app.inject({ method: 'GET', url: '/api/agent-deck/does-not-exist' })
    // No auth hook → request reaches routing → normal 404 (never 401).
    expect(res.statusCode).toBe(404)
  })

  it('serves the health probe without a token', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => Response.json({ status: 'ok', platform: 'hermes-agent' })) as typeof fetch,
    )
    app = await buildApp(makeConfig('127.0.0.1'), LOOPBACK_AUTH)
    const res = await app.inject({ method: 'GET', url: '/api/agent-deck/health' })
    expect(res.statusCode).toBe(200)
  })

  it('does NOT inject a token into the served shell on loopback', async () => {
    app = await buildApp(makeConfig('127.0.0.1', webDist), LOOPBACK_AUTH)
    const res = await app.inject({ method: 'GET', url: '/' })
    expect(res.statusCode).toBe(200)
    expect(res.body).not.toContain('__AGENT_DECK_TOKEN__')
  })
})

describe('non-loopback bind = token gated', () => {
  it('401s a gated /api path with NO token', async () => {
    app = await buildApp(makeConfig('box.ts.net'), REMOTE_AUTH)
    const res = await app.inject({ method: 'GET', url: '/api/agent-deck/sessions' })
    expect(res.statusCode).toBe(401)
    expect(res.json().error).toBe('unauthorized')
    // The token is never echoed in the error body.
    expect(res.body).not.toContain('SECRET_TOKEN')
  })

  it('401s a gated /api path with a WRONG token', async () => {
    app = await buildApp(makeConfig('box.ts.net'), REMOTE_AUTH)
    const res = await app.inject({
      method: 'GET',
      url: '/api/agent-deck/sessions',
      headers: { authorization: 'Bearer WRONG' },
    })
    expect(res.statusCode).toBe(401)
  })

  it('lets a gated /api path through WITH the correct Bearer token (past the gate)', async () => {
    app = await buildApp(makeConfig('box.ts.net'), REMOTE_AUTH)
    // A path with no route: passing the gate yields a 404 from routing — proving
    // the auth hook let it through rather than 401ing.
    const res = await app.inject({
      method: 'GET',
      url: '/api/agent-deck/does-not-exist',
      headers: { authorization: 'Bearer SECRET_TOKEN' },
    })
    expect(res.statusCode).toBe(404)
  })

  it('keeps the health probe PUBLIC even when gated', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => Response.json({ status: 'ok', platform: 'hermes-agent' })) as typeof fetch,
    )
    app = await buildApp(makeConfig('box.ts.net'), REMOTE_AUTH)
    const res = await app.inject({ method: 'GET', url: '/api/agent-deck/health' })
    expect(res.statusCode).toBe(200)
  })

  it('does NOT gate the SPA shell or static assets (only /api/*)', async () => {
    app = await buildApp(makeConfig('box.ts.net', webDist), REMOTE_AUTH)
    const root = await app.inject({ method: 'GET', url: '/' })
    expect(root.statusCode).toBe(200)
    const deep = await app.inject({ method: 'GET', url: '/sessions/x' })
    expect(deep.statusCode).toBe(200)
  })

  it('does NOT inject the access token into the served shell', async () => {
    app = await buildApp(makeConfig('box.ts.net', webDist), REMOTE_AUTH)
    const res = await app.inject({ method: 'GET', url: '/' })
    expect(res.statusCode).toBe(200)
    expect(res.body).not.toContain('SECRET_TOKEN')
    expect(res.body).not.toContain('__AGENT_DECK_TOKEN__')
    // The deep-link fallback shell is public too.
    const deep = await app.inject({ method: 'GET', url: '/sessions/x' })
    expect(deep.body).not.toContain('SECRET_TOKEN')
    expect(deep.body).not.toContain('__AGENT_DECK_TOKEN__')
  })

  it('uses /auth/check as a gated token verification route', async () => {
    app = await buildApp(makeConfig('box.ts.net'), REMOTE_AUTH)
    const missing = await app.inject({ method: 'GET', url: '/api/agent-deck/auth/check' })
    expect(missing.statusCode).toBe(401)

    const ok = await app.inject({
      method: 'GET',
      url: '/api/agent-deck/auth/check',
      headers: { authorization: 'Bearer SECRET_TOKEN' },
    })
    expect(ok.statusCode).toBe(200)
    expect(ok.json()).toEqual({ ok: true })
  })
})
