/**
 * AUTH — the C1 access gate for non-loopback binds.
 *
 * THREAT MODEL: on a pure loopback bind (127.0.0.1 / localhost / ::1) the only
 * client is the user on the same machine, so the app is frictionless — NO auth.
 * The moment the server binds a NON-loopback host (a Tailscale name/IP, a LAN
 * address, 0.0.0.0, …) OR the operator forces a remote/proxied posture, it
 * becomes reachable by other machines, so EVERY `/api/*` request (except the
 * public health probe) and BOTH Socket.IO handshakes (`/chat-run`,
 * `/agent-deck-terminal`) must carry a shared bearer token.
 *
 * SHARED C1 CONTRACT (server half):
 *  - Token = `process.env.AGENT_DECK_TOKEN`, or — if unset on a gated posture —
 *    an auto-generated token printed ONCE at startup.
 *  - The server NEVER injects the token into index.html. A remote/proxied
 *    browser enters the token manually; the browser stores it locally and sends
 *    it as `Authorization: Bearer <t>` on fetches and as the socket handshake
 *    `auth: { token }`.
 *  - The server accepts EITHER the Bearer header OR the socket `auth.token` and
 *    401s a mismatch when auth is required.
 *
 * SECURITY: the token is a credential. It is printed to the server console once
 * (operator-facing), but never logged per-request, never injected into HTML, and
 * never echoed in error bodies.
 */
import { randomBytes } from 'node:crypto'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { homedir } from 'node:os'
import { join, dirname } from 'node:path'

/** Hostnames that mean "this machine only" — no auth required on these binds. */
const LOOPBACK_HOSTS = new Set(['127.0.0.1', 'localhost', '::1', '0:0:0:0:0:0:0:1'])

/**
 * Is this bind host a loopback address? Loopback = frictionless (no auth);
 * anything else is treated as remotely reachable and requires the token. IPv6
 * binds may arrive bracketed (`[::1]`); strip the brackets before comparing.
 */
export function isLoopbackHost(host: string): boolean {
  const h = host.trim().toLowerCase().replace(/^\[/, '').replace(/\]$/, '')
  return LOOPBACK_HOSTS.has(h)
}

export interface AuthConfig {
  /** Whether this bind requires a token (true on a non-loopback host). */
  required: boolean
  /** The shared bearer token. Empty string when auth is not required. */
  token: string
  /** True when the token was auto-generated (so startup can print it). */
  autoGenerated: boolean
}

/** Auth is forced when a loopback service is exposed by a proxy (e.g. Tailscale Serve). */
function authForcedByEnv(env: NodeJS.ProcessEnv): boolean {
  return env.AGENT_DECK_FORCE_AUTH === '1' || env.AGENT_DECK_REMOTE === '1'
}

/**
 * Resolve the auth posture for a given bind host + environment.
 *
 * - Loopback bind → `{ required: false, token: '', autoGenerated: false }`
 *   unless `AGENT_DECK_FORCE_AUTH=1` or `AGENT_DECK_REMOTE=1` is set.
 * - Remote/forced bind → required; token from `AGENT_DECK_TOKEN` when set,
 *   otherwise a freshly generated 256-bit hex token (`autoGenerated = true`).
 *
 * `gen` is injectable so tests get a deterministic token.
 */
export function resolveAuth(
  host: string,
  env: NodeJS.ProcessEnv = process.env,
  gen: () => string = generateToken,
): AuthConfig {
  if (isLoopbackHost(host) && !authForcedByEnv(env)) {
    return { required: false, token: '', autoGenerated: false }
  }
  const fromEnv = env.AGENT_DECK_TOKEN?.trim()
  if (fromEnv) {
    return { required: true, token: fromEnv, autoGenerated: false }
  }
  return { required: true, token: gen(), autoGenerated: true }
}

/** A cryptographically-random 256-bit token, hex-encoded. */
export function generateToken(): string {
  return randomBytes(32).toString('hex')
}

/** Default path for the persisted auto-generated bearer token (deck-owned, 0600). */
export function defaultTokenPath(home: string = homedir()): string {
  return join(home, '.agent-deck', 'auth-token')
}

/**
 * Load the persisted auto-generated token, or create + persist a fresh one. Used as
 * {@link resolveAuth}'s `gen` on the real server so the auto-generated token is
 * STABLE across restarts — a remote operator who unlocked once isn't silently locked
 * out when the service restarts (the previous behavior generated a new token every
 * boot). The file is written 0600 inside a 0700 dir. If it can't be read/written
 * (read-only FS), falls back to an in-memory token — it just won't survive a restart.
 */
export function loadOrCreatePersistedToken(path: string = defaultTokenPath()): string {
  try {
    const existing = readFileSync(path, 'utf8').trim()
    if (existing) return existing
  } catch {
    // Not present yet (or unreadable) — create one below.
  }
  const token = generateToken()
  try {
    mkdirSync(dirname(path), { recursive: true, mode: 0o700 })
    writeFileSync(path, token, { encoding: 'utf8', mode: 0o600 })
  } catch {
    // Can't persist (e.g. read-only FS) — return the in-memory token anyway.
  }
  return token
}

/** The shape of a Socket.IO handshake we read for auth (subset, injectable). */
export interface SocketHandshakeLike {
  auth?: Record<string, unknown>
  headers?: Record<string, string | string[] | undefined>
}

/**
 * Validate a Socket.IO handshake against the auth config. Accepts the token
 * from `handshake.auth.token` (the primary path the browser uses) OR an
 * `Authorization: Bearer` header on the handshake request. Returns true when
 * auth is not required (loopback) or the token matches.
 */
export function socketHandshakeOk(auth: AuthConfig, handshake: SocketHandshakeLike): boolean {
  if (!auth.required) return true
  const fromAuth = handshake.auth?.token
  if (typeof fromAuth === 'string' && tokensMatch(auth.token, fromAuth)) return true
  const header = handshake.headers?.authorization
  const headerValue = Array.isArray(header) ? header[0] : header
  return tokensMatch(auth.token, bearerFromHeader(headerValue))
}

/** Extract the bearer credential from an `Authorization` header value, or null. */
export function bearerFromHeader(header: string | undefined): string | null {
  if (!header) return null
  const match = /^Bearer\s+(.+)$/i.exec(header.trim())
  return match ? match[1]!.trim() : null
}

/**
 * Constant-time-ish token comparison. Tokens are fixed-length hex, but compare
 * defensively: reject on length mismatch, then compare every char so a partial
 * match does not short-circuit and leak length via timing.
 */
export function tokensMatch(expected: string, provided: string | null | undefined): boolean {
  if (!expected || !provided) return false
  if (provided.length !== expected.length) return false
  let diff = 0
  for (let i = 0; i < expected.length; i++) {
    diff |= expected.charCodeAt(i) ^ provided.charCodeAt(i)
  }
  return diff === 0
}

/** Request paths that are PUBLIC even on a non-loopback bind (no token). */
const PUBLIC_PATHS = new Set(['/api/agent-deck/health'])

/**
 * Should this request path be auth-gated? Only `/api/*` is gated, and the public
 * health probe is exempt. Static assets, the SPA shell, and socket polling
 * (handled separately by the namespace middleware) are NOT gated here.
 * The query string is ignored.
 */
export function isGatedApiPath(rawUrl: string): boolean {
  const path = rawUrl.split('?')[0] ?? rawUrl
  if (!path.startsWith('/api/')) return false
  return !PUBLIC_PATHS.has(path)
}
