import { describe, it, expect, afterEach, vi } from 'vitest'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { buildApp } from './app'
import { HealthResponse, Organization } from '@agent-deck/protocol'
import type { ServerConfig } from './config'

let app: Awaited<ReturnType<typeof buildApp>> | undefined
afterEach(async () => {
  vi.restoreAllMocks()
  vi.unstubAllGlobals()
  await app?.close()
  app = undefined
})

const testConfig: ServerConfig = {
  host: '127.0.0.1',
  port: 7878,
  remote: false,
  trustedHosts: [],
  terminalEnabled: true,
  terminalAllowHome: false,
  terminalParkGraceMs: 60_000,
  hermesHome: '/tmp/hermes-test-home',
  hermesGatewayUrl: 'http://127.0.0.1:8643',
  hermesBin: '/tmp/hermes',
  hermesApiKey: null,
  hermesDashboardUrl: 'http://127.0.0.1:9123',
  hermesDashboardHost: '127.0.0.1:9123',
  webClientRoot: null,
  mcpCatalogDir: '/tmp/optional-mcps',
}

describe('GET /api/agent-deck/health', () => {
  it('returns a contract-valid health payload when Hermes is reachable', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () =>
        Response.json({ status: 'ok', platform: 'hermes-agent' }),
      ) satisfies typeof fetch,
    )

    app = await buildApp(testConfig)
    const res = await app.inject({ method: 'GET', url: '/api/agent-deck/health' })

    expect(res.statusCode).toBe(200)
    const parsed = HealthResponse.parse(res.json())
    expect(parsed).toEqual({
      status: 'ok',
      hermes: {
        reachable: true,
        endpoint: 'http://127.0.0.1:8643',
        platform: 'hermes-agent',
      },
      bind: { remote: false, terminalEnabled: true, authRequired: false },
      version: '0.1.0',
    })
    expect(fetch).toHaveBeenCalledWith(new URL('http://127.0.0.1:8643/v1/health'), {
      signal: expect.any(AbortSignal),
    })
  })

  it('degrades gracefully when Hermes is unreachable', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new Error('connection refused')
      }) satisfies typeof fetch,
    )

    app = await buildApp(testConfig)
    const res = await app.inject({ method: 'GET', url: '/api/agent-deck/health' })

    expect(res.statusCode).toBe(200)
    const parsed = HealthResponse.parse(res.json())
    expect(parsed.status).toBe('degraded')
    expect(parsed.hermes).toEqual({
      reachable: false,
      endpoint: 'http://127.0.0.1:8643',
      platform: null,
    })
  })

  it('surfaces a remote bind posture (remote + gated terminal) so the client can be honest', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () =>
        Response.json({ status: 'ok', platform: 'hermes-agent' }),
      ) satisfies typeof fetch,
    )
    const remoteConfig: ServerConfig = {
      ...testConfig,
      host: 'box.tail1234.ts.net',
      remote: true,
      terminalEnabled: false,
    }
    app = await buildApp(remoteConfig, { required: true, token: 'T', autoGenerated: false })
    const res = await app.inject({
      method: 'GET',
      url: '/api/agent-deck/health',
      // Host-allowlist hook accepts the bound host; the health probe is public.
      headers: { host: 'box.tail1234.ts.net:7878' },
    })
    expect(res.statusCode).toBe(200)
    const parsed = HealthResponse.parse(res.json())
    expect(parsed.bind).toEqual({ remote: true, terminalEnabled: false, authRequired: true })
  })
})

describe('organization routes wiring', () => {
  it('registers the organization store under a fresh hermes home', async () => {
    const home = await mkdtemp(join(tmpdir(), 'agent-deck-app-org-'))
    try {
      app = await buildApp({ ...testConfig, hermesHome: home })
      const res = await app.inject({ method: 'GET', url: '/api/agent-deck/organization' })
      expect(res.statusCode).toBe(200)
      expect(Organization.parse(res.json())).toEqual({ projects: [], assignments: {} })
    } finally {
      await rm(home, { recursive: true, force: true })
    }
  })
})

describe('global error handler — no exception message ever leaks to a client', () => {
  it('a malformed config.yaml on an MCP mutation returns a generic 500, never the config contents', async () => {
    const home = await mkdtemp(join(tmpdir(), 'agent-deck-badcfg-'))
    try {
      // An unterminated quote on a credential line: the yaml parser's message would
      // echo this secret. The route reads the config BEFORE its try, so the throw
      // escapes the handler — the global error handler must sanitize it.
      await writeFile(
        join(home, 'config.yaml'),
        'API_SERVER_KEY: "leaky-secret-unterminated\nmodel: x\n',
        'utf8',
      )
      app = await buildApp({ ...testConfig, hermesHome: home })
      const res = await app.inject({ method: 'DELETE', url: '/api/agent-deck/mcp/context7' })
      expect(res.statusCode).toBe(500)
      expect(res.body).not.toContain('leaky-secret')
      expect(res.json()).toEqual({ error: 'internal_error' })
    } finally {
      await rm(home, { recursive: true, force: true })
    }
  })
})

describe('connections surface is registered (anti-recurrence: the plugin shipped unregistered)', () => {
  it('mounts pairing/webhooks/credentials — they degrade to an upstream error, never a 404 not_found', async () => {
    // The dashboard is unreachable in the test, so each route returns an honest
    // upstream error (502/500) — NOT the not-found handler's 404. If the plugin were
    // unregistered (the bug this guards against), every one of these would 404
    // not_found and the three Connections tabs would be permanently broken.
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new Error('dashboard unreachable in test')
      }) satisfies typeof fetch,
    )
    app = await buildApp(testConfig)
    for (const url of [
      '/api/agent-deck/pairing',
      '/api/agent-deck/webhooks',
      '/api/agent-deck/credentials/pool',
    ]) {
      const res = await app.inject({ method: 'GET', url })
      expect(res.statusCode).not.toBe(404)
    }
  })
})
