/**
 * I4 — security response headers (helmet) + Host-allowlist hook.
 *
 * Hermetic: drives the real Fastify app via inject. Verifies the hardening
 * headers are present on a normal response, that the Host-allowlist hook rejects
 * a foreign Host (DNS-rebinding defense) while accepting loopback / *.ts.net /
 * the bound host, and that /files/raw keeps its own strict CSP.
 */
import { describe, it, expect, afterEach, beforeAll, afterAll, vi } from 'vitest'
import { mkdtempSync, writeFileSync, rmSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { buildApp, isAllowedHost, isAllowedOrigin } from './app'
import type { ServerConfig } from './config'
import { isLoopbackHost, type AuthConfig } from './auth/auth'

let webDist: string
beforeAll(() => {
  webDist = mkdtempSync(join(tmpdir(), 'agent-deck-sec-dist-'))
  writeFileSync(
    join(webDist, 'index.html'),
    '<!doctype html><html><head><title>Agent Deck</title></head><body><div id="root"></div></body></html>',
  )
  mkdirSync(join(webDist, 'assets'))
  writeFileSync(join(webDist, 'assets', 'app.js'), 'console.log("hi")')
})
afterAll(() => {
  rmSync(webDist, { recursive: true, force: true })
})

function makeConfig(host: string, staticRoot: string | null = null): ServerConfig {
  const remote = !isLoopbackHost(host)
  return {
    host,
    port: 7878,
    remote,
    trustedHosts: [],
    terminalEnabled: !remote,
    terminalAllowHome: false,
    terminalParkGraceMs: 60_000,
    hermesHome: '/tmp/hermes-test-home',
    hermesGatewayUrl: 'http://127.0.0.1:8643',
    hermesBin: '/tmp/hermes',
    hermesApiKey: null,
    hermesDashboardUrl: 'http://127.0.0.1:9123',
    hermesDashboardHost: '127.0.0.1:9123',
    webClientRoot: staticRoot,
    mcpCatalogDir: '/tmp/optional-mcps',
  }
}

const LOOPBACK_AUTH: AuthConfig = { required: false, token: '', autoGenerated: false }

let app: Awaited<ReturnType<typeof buildApp>> | undefined
afterEach(async () => {
  vi.restoreAllMocks()
  await app?.close()
  app = undefined
})

describe('isAllowedHost', () => {
  it('accepts loopback / *.ts.net / the bound host (port-insensitive)', () => {
    expect(isAllowedHost('127.0.0.1:7878', '127.0.0.1')).toBe(true)
    expect(isAllowedHost('localhost:5173', '127.0.0.1')).toBe(true)
    expect(isAllowedHost('[::1]:7878', '127.0.0.1')).toBe(true)
    expect(isAllowedHost('my-box.tail123.ts.net', '127.0.0.1')).toBe(true)
    expect(isAllowedHost('my-box.ts.net:7878', 'my-box.ts.net')).toBe(true)
  })
  it('rejects a foreign Host (DNS rebinding)', () => {
    expect(isAllowedHost('evil.example.com', '127.0.0.1')).toBe(false)
    expect(isAllowedHost('attacker.test:7878', '127.0.0.1')).toBe(false)
  })
  it('rejects a missing Host header', () => {
    expect(isAllowedHost(undefined, '127.0.0.1')).toBe(false)
  })
})

describe('trusted hosts (reverse-proxy / custom-domain allowlist)', () => {
  const trusted = ['deck.example.com', 'agent.acme.io']
  it('accepts a configured trusted Host that is not loopback/ts.net/bound (port-insensitive)', () => {
    expect(isAllowedHost('deck.example.com', '127.0.0.1', trusted)).toBe(true)
    expect(isAllowedHost('deck.example.com:8080', '127.0.0.1', trusted)).toBe(true)
    expect(isAllowedHost('agent.acme.io', '127.0.0.1', trusted)).toBe(true)
  })
  it('accepts a configured trusted Origin (CORS + WS handshake)', () => {
    expect(isAllowedOrigin('https://deck.example.com', '127.0.0.1', trusted)).toBe(true)
    expect(isAllowedOrigin('https://deck.example.com:8443', '127.0.0.1', trusted)).toBe(true)
  })
  it('still rejects a Host/Origin NOT in the trusted list', () => {
    expect(isAllowedHost('evil.example.com', '127.0.0.1', trusted)).toBe(false)
    expect(isAllowedOrigin('https://evil.example.com', '127.0.0.1', trusted)).toBe(false)
  })
  it('with no trusted hosts (default), a custom domain is rejected exactly as before', () => {
    expect(isAllowedHost('deck.example.com', '127.0.0.1')).toBe(false)
    expect(isAllowedOrigin('https://deck.example.com', '127.0.0.1')).toBe(false)
  })
})

describe('security headers on responses', () => {
  it('sets nosniff, frame-deny, and a CSP on the served shell', async () => {
    app = await buildApp(makeConfig('127.0.0.1', webDist), LOOPBACK_AUTH)
    const res = await app.inject({
      method: 'GET',
      url: '/',
      headers: { host: '127.0.0.1:7878' },
    })
    expect(res.statusCode).toBe(200)
    expect(res.headers['x-content-type-options']).toBe('nosniff')
    expect(res.headers['x-frame-options']).toBe('DENY')
    const csp = res.headers['content-security-policy']
    expect(csp).toBeTruthy()
    expect(String(csp)).toContain("frame-ancestors 'none'")
    // 'wasm-unsafe-eval' must stay in script-src so the syntax-highlighter's
    // Oniguruma WASM regex engine (Shiki) can instantiate. Removing it makes
    // WebAssembly.instantiate throw a CSP CompileError and ALL code highlighting
    // silently falls back to plain text. It permits WASM only, never JS eval.
    expect(String(csp)).toContain("'wasm-unsafe-eval'")
  })

  it('sets hardening headers on the health JSON response too', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => Response.json({ status: 'ok', platform: 'hermes-agent' })) as typeof fetch,
    )
    app = await buildApp(makeConfig('127.0.0.1'), LOOPBACK_AUTH)
    const res = await app.inject({
      method: 'GET',
      url: '/api/agent-deck/health',
      headers: { host: '127.0.0.1:7878' },
    })
    expect(res.statusCode).toBe(200)
    expect(res.headers['x-content-type-options']).toBe('nosniff')
  })

  // /files/raw keeps its own strict per-route CSP (default-src 'none'); that
  // contract is asserted directly in src/files/routes.test.ts where a real files
  // root is wired with the mock dashboard.
})

describe('isAllowedOrigin (CORS origin allowlist)', () => {
  it('accepts loopback origins regardless of bound host', () => {
    expect(isAllowedOrigin('http://127.0.0.1:5173', '127.0.0.1')).toBe(true)
    expect(isAllowedOrigin('http://localhost:5173', '127.0.0.1')).toBe(true)
    expect(isAllowedOrigin('http://[::1]:5173', '127.0.0.1')).toBe(true)
  })

  it('accepts origins matching the EXACT bound ts.net hostname (not any *.ts.net)', () => {
    expect(isAllowedOrigin('https://my-box.tail1234.ts.net', 'my-box.tail1234.ts.net')).toBe(true)
  })

  it('rejects a different ts.net hostname when a specific ts.net host is bound', () => {
    expect(isAllowedOrigin('https://other-box.tail1234.ts.net', 'my-box.tail1234.ts.net')).toBe(
      false,
    )
    expect(isAllowedOrigin('https://attacker.ts.net', 'my-box.tail1234.ts.net')).toBe(false)
  })

  it('accepts any *.ts.net origin when bound to a loopback host (no ts.net restriction)', () => {
    // When bound to loopback (127.0.0.1), any ts.net origin is allowed — the user
    // accesses via Tailscale Serve from their specific ts.net hostname, but we
    // don't know which one at bind time. The Host-allowlist is the real guard.
    expect(isAllowedOrigin('https://some-box.ts.net', '127.0.0.1')).toBe(true)
  })

  it('accepts a missing origin (same-origin / server-to-server)', () => {
    expect(isAllowedOrigin(undefined, '127.0.0.1')).toBe(true)
  })

  it('rejects a fully foreign origin', () => {
    expect(isAllowedOrigin('https://evil.example.com', '127.0.0.1')).toBe(false)
  })
})

describe('Fastify bodyLimit (payload size guard)', () => {
  it('returns 413 when the request body exceeds the configured limit', async () => {
    app = await buildApp(makeConfig('127.0.0.1'), LOOPBACK_AUTH)
    // Send a payload larger than the DEFAULT_BODY_LIMIT (1MB). We test with
    // a 2MB JSON body — the error should be 413, not a silent drop.
    const big = JSON.stringify({ data: 'x'.repeat(1_200_000) })
    const res = await app.inject({
      method: 'POST',
      url: '/api/agent-deck/cli-op',
      headers: { host: '127.0.0.1:7878', 'content-type': 'application/json' },
      body: big,
    })
    expect(res.statusCode).toBe(413)
  })
})

describe('Host-allowlist hook (DNS-rebinding defense)', () => {
  it('rejects a request with a foreign Host header', async () => {
    app = await buildApp(makeConfig('127.0.0.1'), LOOPBACK_AUTH)
    const res = await app.inject({
      method: 'GET',
      url: '/api/agent-deck/health',
      headers: { host: 'evil.example.com' },
    })
    expect(res.statusCode).toBe(421)
    expect(res.json().error).toBe('misdirected_host')
  })

  it('accepts a request whose Host matches the bound (Tailscale) host', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => Response.json({ status: 'ok', platform: 'hermes-agent' })) as typeof fetch,
    )
    app = await buildApp(makeConfig('my-box.ts.net'), {
      required: true,
      token: 'T',
      autoGenerated: false,
    })
    const res = await app.inject({
      method: 'GET',
      url: '/api/agent-deck/health',
      headers: { host: 'my-box.ts.net:7878' },
    })
    expect(res.statusCode).toBe(200)
  })
})
