/**
 * C1 — /chat-run handshake auth (server half). On a non-loopback bind the chat
 * namespace must reject a handshake that lacks the shared token, and accept one
 * that carries it as `auth: { token }`. Hermetic: a stub gateway (never called
 * because we only test the handshake, before any `run` command) keeps this off
 * the network.
 */
import { describe, it, expect, afterEach } from 'vitest'
import { createServer, type Server as HttpServer } from 'node:http'
import type { AddressInfo } from 'node:net'
import { Server as SocketIOServer } from 'socket.io'
import { io as ioClient, type Socket as ClientSocket } from 'socket.io-client'
import { registerChatRunHandlers, CHAT_NAMESPACE } from './chatRun'
import type { GatewayClientLike } from '../hermes/gatewayClient'
import type { AuthConfig } from '../auth/auth'

const stubGateway = {
  // eslint-disable-next-line require-yield
  async *streamRun() {
    return
  },
  async startRun() {
    return { runId: 'r' }
  },
  async stopRun() {},
  async respondApproval() {},
} as unknown as GatewayClientLike

let http: HttpServer | undefined
let io: SocketIOServer | undefined
const clients: ClientSocket[] = []

afterEach(async () => {
  for (const c of clients.splice(0)) c.disconnect()
  await io?.close()
  io = undefined
  if (http) {
    const server = http
    await new Promise<void>((resolve) => server.close(() => resolve()))
  }
  http = undefined
})

async function boot(auth: AuthConfig): Promise<string> {
  http = createServer()
  io = new SocketIOServer(http)
  registerChatRunHandlers(io, { gateway: stubGateway, auth })
  await new Promise<void>((resolve) => http!.listen(0, '127.0.0.1', resolve))
  const { port } = http!.address() as AddressInfo
  return `http://127.0.0.1:${port}`
}

function connect(url: string, opts: Record<string, unknown> = {}): ClientSocket {
  const c = ioClient(`${url}${CHAT_NAMESPACE}`, {
    transports: ['websocket'],
    forceNew: true,
    ...opts,
  })
  clients.push(c)
  return c
}

function waitConnectOrError(c: ClientSocket): Promise<'connected' | 'error'> {
  return new Promise((resolve) => {
    c.on('connect', () => resolve('connected'))
    c.on('connect_error', () => resolve('error'))
  })
}

const AUTH: AuthConfig = { required: true, token: 'CHAT_TOKEN', autoGenerated: false }

describe('/chat-run handshake auth (non-loopback bind)', () => {
  it('connects with the matching token', async () => {
    const url = await boot(AUTH)
    const c = connect(url, { auth: { token: 'CHAT_TOKEN' } })
    expect(await waitConnectOrError(c)).toBe('connected')
  })

  it('refuses with no token', async () => {
    const url = await boot(AUTH)
    const c = connect(url)
    expect(await waitConnectOrError(c)).toBe('error')
  })

  it('refuses with a wrong token', async () => {
    const url = await boot(AUTH)
    const c = connect(url, { auth: { token: 'NOPE' } })
    expect(await waitConnectOrError(c)).toBe('error')
  })

  it('is frictionless (no token needed) when auth is not required (loopback)', async () => {
    const url = await boot({ required: false, token: '', autoGenerated: false })
    const c = connect(url)
    expect(await waitConnectOrError(c)).toBe('connected')
  })
})
